name: Performance Audit

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: |
          node -v
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Waiting for 200 from the Netlify Preview
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netflify-preview
        with:
          site_name: 'phq9'
      - name: Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        with:
          urls: |
            $DEPLOY_URL/
            $DEPLOY_URL/questionnaire
            $DEPLOY_URL/therapists/list
            $DEPLOY_URL/therapists/1/details
          runs: 1
          budgetPath: ./perf/budget.json
        env:
          DEPLOY_URL: ${{ steps.wait-for-netflify-preview.outputs.url }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Save results
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-results
          path: '.lighthouseci'
